### ISSUE TITLE
Basic `adhara-CLI` framework to help developers coordinate components (start, stop, check status, create default config settings etc)

### ISSUE THREAD

**Issue by JasoonS** [AdharaProjects/cbs-proxy#10]
Using Oclif at the moment, I tried a few other frameworks such as commander, yargs, inquirer. But Oclif seems best (if you have input experience let me know).

I'm planning to use configstore npm package to handle default configs for the commands which users can configure, tag and use depending on their usecase.

**Comment by rynobey** [comment]
Re-created in admin-cli repo
