### ISSUE TITLE
Rename to cyclos-proxy

### ISSUE THREAD

**Issue by rynobey** [AdharaProjects/cbs-proxy#26]
Since the cbs-proxy is currently specifically made to work with cyclos, perhaps we should consider renaming it to cyclos-proxy (and perhaps some work is needed to genericize the cbs-proxy-client as well)?

**Comment by coeniebeyers** [comment]
Even though the cbs-proxy is currently specifically catering for Cyclos, only once we start integrating with another CBS will we be able to know how and what to generalise. I'd prefer to address this question once we actually get to integrate into a different CBS. If possible, we'd ideally be able to do some work, even if significant, and separate out the unique cyclos things into a cyclos connector that the cbs-proxy uses. Ideally, we can also have a (for example) Themenos connector, which the cbs-proxy can just `require` and based on a config setting the cbs-proxy can pick which connector to use.

**Comment by JasoonS** [comment]
Yes, exactly what Coenie said.  That way very little code will need to be changed in our core system when integrating with different CBSs.

It might be more messy than we anticipate, but we can at least try :)

**Comment by deklerkmc** [comment]
Decision to address when another CBS comes into the picture
