### ISSUE TITLE
Move the login process to parallel rather than sequential

### ISSUE THREAD

**Issue by RobKirch132** [AdharaProjects/cbs-proxy#36]
Once we have completed the investigation around polling the CBS and a subscription service, we can also look at the login process to improve performance.

**Comment by JasoonS** [comment]
https://github.com/AdharaProjects/cbs-proxy/issues/42 <- for phase 2 of this we can use this change.

For now login will have to be 2 steps (currently it is 6 sequential calls!)

**Comment by deklerkmc** [comment]
Can we close this?
