### ISSUE TITLE
List endpoints, check naming + RESTfulness

### ISSUE THREAD

**Issue by JasoonS** [AdharaProjects/cbs-proxy#40]
We should come up with a logical, standard and uniform way of expresing these endpoints. At the moment it is very messy, since the functions were just added to get something working. Now that we have some perspective we can start to decide how to do this properly.

Some discussion around this here: https://github.com/AdharaProjects/cbs-proxy/pull/29#issuecomment-419342698

**Comment by coeniebeyers** [comment]
Agreed, once we have something demo-able we can enter a phase where we do some housekeeping. I think we are nearly there, especially once https://github.com/AdharaProjects/cbs-proxy/issues/36 and https://github.com/AdharaProjects/cash-tokenizer-ui/issues/133 have been sorted

**Comment by deklerkmc** [comment]
I'll create a spreadsheet listing all the endpoints across the system along with columns to mark them as RESTful, etc.

The intention is not to be a living document that must be maintained - just once off.

*replace this with link to doc*

**Comment by JasoonS** [comment]
I don't see the reason why it should be a once off. We can use it to track how far we are with making changes and standardising our endpoints; because I think these changes will be spread out over time.

**Comment by deklerkmc** [comment]
You're right, it's better to let it live... 
Also, as mentioned by @rynobey, this can be a reference when creating new endpoints
