### ISSUE TITLE
Create version of `/getAccountsList` that takes a username+password rather than a a session token

### ISSUE THREAD

**Issue by JasoonS** [AdharaProjects/cbs-proxy#42]
This is similar to #43

This will allow us to increase the speed of login even more. 

Currently the best possible is to first get the session token, and then get the account details with the session token.

When this is implemented we will be able to use a `Promise.all` and get all the information directly using the username+password in one step.

child of https://github.com/AdharaProjects/cbs-proxy/issues/36

**Comment by deklerkmc** [comment]
![screenshot 2018-10-02 at 21 06 13](https://user-images.githubusercontent.com/965948/46370856-0adde900-c687-11e8-9443-787649c95fff.png)

This seems to me to be using a `sessionToken`, rather than a `username` and `password`?

**Comment by JasoonS** [comment]
@deklerkmc It is the other way around, it should could be able to use a username+password. But I think we can close
