### ISSUE TITLE
Upgrade cbs-proxy to be compatible with latest cyclos

### ISSUE THREAD

**Issue by JasoonS** [AdharaProjects/cbs-proxy#44]
The latest Cyclos has some performance improvements apparently. And the fix is relatively easy.

When you try send a transfer from the omnibus account to a user you get the following error:
![image](https://user-images.githubusercontent.com/6032276/47227653-0e35dc00-d3cc-11e8-80c0-fbe32e973d91.png)

The fix is simple, add the subject to the request body - then it works:
![image](https://user-images.githubusercontent.com/6032276/47227697-24439c80-d3cc-11e8-86f2-4f6a15041382.png)

**Comment by petermunnings** [comment]
Has this been done yet?

**Comment by JasoonS** [comment]
Won't fix, no need to
